# RHEL 8.8
---
- name: Configure RHEL 8.8 Server
  hosts: all
  become: yes

  tasks:
    - name: Validate RHEL version
      command: cat /etc/redhat-release
      register: rhel_version
      changed_when: false
      failed_when: "'Red Hat Enterprise Linux release 8.8' not in rhel_version.stdout"

    - name: Check Red Hat Subscription
      command: subscription-manager identity
      register: rh_subscription
      changed_when: false
      ignore_errors: true

    - name: Ensure NetworkManager service is running and enabled
      service:
        name: NetworkManager
        state: started
        enabled: yes

    - name: Get active network interface
      command: ip route get 8.8.8.8
      register: active_interface
      changed_when: false

    - name: Get default gateway
      set_fact:
        default_gateway: "{{ active_interface.stdout.split()[2] }}"
      when: active_interface.rc == 0 and active_interface.stdout | length > 0

    - name: ICMP Ping default gateway
      command: "ping -c 1 {{ default_gateway }}"
      changed_when: false
      when: active_interface.rc == 0 and active_interface.stdout | length > 0

    - name: ICMP Ping internet (Google DNS)
      command: "ping -c 1 8.8.8.8"
      changed_when: false
      when: active_interface.rc == 0 and active_interface.stdout | length > 0

    - name: Check for system updates
      yum:
        name: '*'
        state: latest
      register: yum_upgrade

    - name: Display upgrade summary
      debug:
        var: yum_upgrade

    - name: Display IP information of active interface
      command: ip addr show "{{ active_interface.stdout.split()[4] }}"
      register: interface_ip_info
      changed_when: false
      when: active_interface.rc == 0 and active_interface.stdout | length > 0

    - name: Display IP information
      debug:
        var: interface_ip_info.stdout_lines
      when: interface_ip_info.stdout_lines is defined

    - name: Restart if necessary
      reboot:
      when: yum_upgrade.reboot_required|default(false)
