---
- name: Configure RHEL 8.8 Server
  hosts: all
  become: yes

  tasks:
    - name: Check Red Hat Subscription
      command: subscription-manager identity
      register: rh_subscription
      changed_when: false
      ignore_errors: true

    - name: Install NetworkManager if not present
      package:
        name: NetworkManager
        state: latest
      when: rh_subscription.rc == 0

    - name: Ensure NetworkManager service is running and enabled
      service:
        name: NetworkManager
        state: started
        enabled: yes

    - name: Get active network interface
      command: ip route get 8.8.8.8
      register: active_interface
      changed_when: false

    - name: Get default gateway
      set_fact:
        default_gateway: "{{ active_interface.stdout.split()[2] }}"
      when: active_interface.rc == 0 and active_interface.stdout | length > 0

    - name: Ping default gateway
      ping:
        host: "{{ default_gateway }}"
      register: ping_gateway
      until: ping_gateway.ping
      retries: 3
      delay: 5
      when: active_interface.rc == 0 and active_interface.stdout | length > 0

    - name: Ping internet (Google DNS)
      ping:
        host: 8.8.8.8
      register: ping_internet
      until: ping_internet.ping
      retries: 3
      delay: 5
      when: active_interface.rc == 0 and active_interface.stdout | length > 0

    - name: Check for system updates
      yum:
        name: '*'
        state: latest
      register: yum_upgrade

    - name: Display upgrade summary
      debug:
        var: yum_upgrade

    - name: Display IP information of active interface
      command: ip addr show "{{ active_interface.stdout.split()[4] }}"
      register: interface_ip_info
      changed_when: false
      when: active_interface.rc == 0 and active_interface.stdout | length > 0

    - name: Display IP information
      debug:
        var: interface_ip_info.stdout_lines
      when: interface_ip_info.stdout_lines is defined