---
- name: Configure Network and Check Connectivity on RedHat
  hosts: all
  become: yes  # Give us elevated privileges

  tasks:
    # Check if the system is registered with Red Hat
    - name: Check Red Hat Subscription
      command:
        cmd: subscription-manager identity
      register: rh_subscription
      ignore_errors: yes

    # Ensure nmcli is installed
    - name: Check if nmcli is installed
      command:
        cmd: which nmcli
      register: nmcli_check
      ignore_errors: yes

    - name: Install NetworkManager and nmcli if not present
      yum:
        name: NetworkManager
        state: latest
      when: nmcli_check.rc != 0

    # Start and enable NetworkManager service
    - name: Ensure NetworkManager service is running and enabled
      service:
        name: NetworkManager
        state: started
        enabled: yes

    - name: Gather information about ens192
      command:
        cmd: nmcli con show ens192
      register: ens192_info
      ignore_errors: yes  # Continue even if the interface doesn't exist

    - name: Check if ens192 has an IP
      shell:
        cmd: nmcli device show ens192 | grep IP4.ADDRESS
      register: ens192_ip
      ignore_errors: true

    - name: Create ens192 connection
      command:
        cmd: nmcli con add type ethernet ifname ens192 con-name ens192
      when: 
        - "'connection.id: ens192' not in ens192_info.stdout"
        - "'ipv4.method: auto' not in ens192_info.stdout"
        - ens192_ip.stdout == ""

    - name: Set ens192 to use DHCP for IPv4
      command:
        cmd: nmcli con mod ens192 ipv4.method auto
      when: "'ipv4.method: auto' not in ens192_info.stdout"

    - name: Set ens192 to use DHCP for IPv6
      command:
        cmd: nmcli con mod ens192 ipv6.method auto
      when: "'ipv6.method: auto' not in ens192_info.stdout"

    - name: Activate ens192 connection
      command:
        cmd: nmcli con up ens192
      when: ens192_ip.stdout == ""

    # 4. Check for system and package updates
    - name: Check for system updates
      yum:
        name: '*'
        state: latest
      register: yum_upgrade

    - name: Display upgrade summary
      debug:
        var: yum_upgrade
    
    #5. Setup Network
    - name: Get all connection details
      command: "nmcli -t -f NAME,UUID con show"
      register: nmcli_output
      changed_when: False

    - name: Extract UUID for ens224
      set_fact:
        ens192_uuid: "{{ item.split(':')[1] }}"
      loop: "{{ nmcli_output.stdout_lines }}"
      when: "item.split(':')[0] == 'ens224'"
      loop_control:
        label: "{{ item.split(':')[0] }}"

    - name: Set static IP for ens224 using UUID
      nmcli:
        conn_name: "{{ ens224_uuid }}"
        type: ethernet
        state: present
        ip4: '10.50.0.24/24'
        gw4: '10.50.0.1'
        ip6: '2605:1e80:3001:201::24/64'
        gw6: '2605:1e80:3001:201::1'
        dns4:
          - '10.50.0.12'
          - '10.50.0.13'
        dns6:
          - '2605:1e80:3001:201::12'
          - '2605:1e80:3001:201::13'
